import 'package:flutter/material.dart';

class ImageDetails {
  final String imagePath;
  final String price;
  final String photographer;
  final String title;
  final String details;
  ImageDetails({
    @required this.imagePath,
    @required this.price,
    @required this.photographer,
    @required this.title,
    @required this.details,
  });

  static List<ImageDetails> imageList() {
    return [
      ImageDetails(
        imagePath: 'assets/images/f1.jpg',
        price: '\$20.00',
        photographer: 'Martin Andres',
        title: 'New Year',
        details:
            'This image was taken during a party in New York on new years eve. Quite a colorful shot.',
      ),
      ImageDetails(
        imagePath: 'assets/images/f2.jpg',
        price: '\$10.00',
        photographer: 'Abraham Costa',
        title: 'Spring',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f3.jpg',
        price: '\$30.00',
        photographer: 'Jamie Bryan',
        title: 'Casual Look',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f4.jpg',
        price: '\$20.00',
        photographer: 'Jamie Bryan',
        title: 'New York',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f5.jpg',
        price: '\$20.00',
        photographer: 'Jamie Bryan',
        title: 'New York',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f6.jpg',
        price: '\$20.00',
        photographer: 'Jamie Bryan',
        title: 'New York',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f7.jpg',
        price: '\$20.00',
        photographer: 'Jamie Bryan',
        title: 'New York',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f8.jpg',
        price: '\$20.00',
        photographer: 'Jamie Bryan',
        title: 'New York',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f9.jpg',
        price: '\$20.00',
        photographer: 'Jamie Bryan',
        title: 'New York',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f10.jpg',
        price: '\$20.00',
        photographer: 'Jamie Bryan',
        title: 'New York',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f11.jpg',
        price: '\$20.00',
        photographer: 'Jamie Bryan',
        title: 'New York',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f12.jpg',
        price: '\$20.00',
        photographer: 'Jamie Bryan',
        title: 'New York',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f13.jpg',
        price: '\$20.00',
        photographer: 'Jamie Bryan',
        title: 'New York',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f14.jpg',
        price: '\$20.00',
        photographer: 'Matthew',
        title: 'Cone Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f15.jpg',
        price: '\$25.00',
        photographer: 'Martin Sawyer',
        title: 'Pink Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f16.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f17.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f18.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f19.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f20.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f21.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f22.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f23.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f24.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f25.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f26.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f27.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f28.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f29.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f30.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f31.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f32.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f33.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f34.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f35.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f36.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f37.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f38.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f39.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f40.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f41.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f42.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f43.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f44.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f45.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f46.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f47.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
      ImageDetails(
        imagePath: 'assets/images/f48.jpg',
        price: 'Fashion Store',
        photographer: '',
        title: 'Strawberry Ice Cream',
        details: 'Olascut Fashion Designer',
      ),
    ];
  }
}
